### PR TITLE
1.0.0

### PR DESCRIPTION
**Pull request by jpatacz**

### CODE REVIEW

**Comment by flskillcorner** [comment]
Missed it : I would say that we should not use heavy request in example.py, first one is client.get_matches() that takes a really lots of time.
This file should be composed of command example that we recommand, so don't hesitate to add filter to examples.
Another point : for the authent, maybe it's clearer to say something like : _client = SkillcornerClient(username='PUT_YOUR_LOGIN_HERE', password='PUT_YOUR_PASSWORD_HERE')_

**Comment by jpatacz** [comment]
I've succeeded to increment patch version in setup.py file and commit it to the repository during action workflow. The only problem I see is for the first merge of the new version (when releasing e.g. '1.0.0', '2.0.0', '2.1.0'...).  We don't want to increment it this time, but we do want to increment it next time (when releasing e.g. '1.0.1', '2.0.1', '2.1.1'...). 

I can add condition statement for workflow steps incrementing version, but this condition will assume specific branch naming convention (meaning: e.g. '1.1.1', '1.1.2'... for patches being merged into '1.1.0' version branch). Can we agree on such restrictions?

**Comment by flskillcorner** [comment]
> I've succeeded to increment patch version in setup.py file and commit it to the repository during action workflow. The only problem I see is for the first merge of the new version (when releasing e.g. '1.0.0', '2.0.0', '2.1.0'...). We don't want to increment it this time, but we do want to increment it next time (when releasing e.g. '1.0.1', '2.0.1', '2.1.1'...).
> 
> I can add condition statement for workflow steps incrementing version, but this condition will assume specific branch naming convention (meaning: e.g. '1.1.1', '1.1.2'... for patches being merged into '1.1.0' version branch). Can we agree on such restrictions?

**Comment by flskillcorner** [comment]
If I get it : you succesed to update version in setup for each accepted PR ?
If yes, I see an "easy" solution : when we create a branch for new major version, we generally push starting code directly : in this case there is no PR, so we should not have a pre-hook treatment that automatically change version in setup.py ?

**Comment by jpatacz** [comment]
@flskillcorner yes, I've succeeded to update version in setup at closing PR.

Yes, indeed, that's the simplest solution.

**Comment by flskillcorner** [comment]
When I run `python example.py`, I've got this Exception (after almost 2 minutes), do you face the same issue ?
Traceback (most recent call last):
```
  File "/home/franck/envi/skillpy/lib/python3.7/site-packages/urllib3-1.26.7-py3.7.egg/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/franck/envi/skillpy/lib/python3.7/site-packages/urllib3-1.26.7-py3.7.egg/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.7/http/client.py", line 1352, in getresponse
    response.begin()
  File "/usr/lib/python3.7/http/client.py", line 310, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.7/http/client.py", line 271, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.7/ssl.py", line 1052, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.7/ssl.py", line 911, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/franck/envi/skillpy/lib/python3.7/site-packages/requests-2.26.0-py3.7.egg/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/franck/envi/skillpy/lib/python3.7/site-packages/urllib3-1.26.7-py3.7.egg/urllib3/connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/franck/envi/skillpy/lib/python3.7/site-packages/urllib3-1.26.7-py3.7.egg/urllib3/util/retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/franck/envi/skillpy/lib/python3.7/site-packages/urllib3-1.26.7-py3.7.egg/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/home/franck/envi/skillpy/lib/python3.7/site-packages/urllib3-1.26.7-py3.7.egg/urllib3/connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "/home/franck/envi/skillpy/lib/python3.7/site-packages/urllib3-1.26.7-py3.7.egg/urllib3/connectionpool.py", line 447, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/home/franck/envi/skillpy/lib/python3.7/site-packages/urllib3-1.26.7-py3.7.egg/urllib3/connectionpool.py", line 337, in _raise_timeout
    self, url, "Read timed out. (read timeout=%s)" % timeout_value
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='skillcorner.com', port=443): Read timed out. (read timeout=30)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "example.py", line 53, in <module>
    data = client.get_match_video_tracking_data(match_id=60113, params={"frame__gt": 60000})
  File "<makefun-gen-25>", line 2, in get_match_video_tracking_data
  File "/home/franck/git_rep/skillcorner-py/skillcorner/client.py", line 158, in wrapper
    return func(*args, **kwargs)
  File "/home/franck/git_rep/skillcorner-py/skillcorner/client.py", line 418, in _get_data_with_id
    paginated_request=paginated_request)
  File "/home/franck/git_rep/skillcorner-py/skillcorner/client.py", line 114, in wrapper
    return func(*args, **kwargs)
  File "/home/franck/git_rep/skillcorner-py/skillcorner/client.py", line 320, in _skillcorner_request
    timeout=timeout)
  File "/home/franck/envi/skillpy/lib/python3.7/site-packages/requests-2.26.0-py3.7.egg/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/franck/envi/skillpy/lib/python3.7/site-packages/requests-2.26.0-py3.7.egg/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/franck/envi/skillpy/lib/python3.7/site-packages/requests-2.26.0-py3.7.egg/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='skillcorner.com', port=443): Read timed out. (read timeout=30)
```

**Comment by flskillcorner** [comment]
Strange, for me, endpoint  /api/match/60113/video/tracking?frame__gt=60000 is responding well (after 10-15s)
What kind of error do you have when you make a simple request ? (without client)

**Comment by jpatacz** [comment]
504 (Timeout Gateway° I guess it was the fault of the poor network connection. It works fine on this morning.

**Comment by jpatacz** [comment]
Indeed, for documentation page generated by swagger additional setting 'DEEP_LINKING' needs to be enabled in the application, to let url anchoring work without reloading the page. Related PR created in the application repository.

**Pull request merged**
